application: rdf-translator
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /parse
  script: main.py

- url: /
  static_files: index.html
  upload: index.html
